#!/bin/bash

# This script is designed to install and setup all software on Arch Linux.
########################################
# NOTES
# Install git as an additional package when prompted to quickly clone this repo.
# If using archinstall, select Minimal option when prompted.
# After initial install, reboot and login into user.  Then clone this repo to $HOME/dotfiles and then run $HOME/dotfiles/scripts/install/arch.

# Software
#   i3-gaps                 Window manager
#       rofi                    Application launcher
#       feh                     Image viewer to set background
#       playerctl               Media player controller
#       betterlockscreen        Lock screen
#       xautolock               Timer to lock after inactivity
#   polybar                 Status bar
#       dbus-python             Display spotify info module
#   picom                   Compositor
#   alacritty               Terminal emulator
#   zsh                     Shell
#       oh-my-zsh               Zsh framework
#           gnu-free-fonts          Font for various symbols
#   neovim                  Text editor
#   tmux                    Terminal multiplexer
#   nvidia                  Graphics driver
#       nvidia-settings         Tool to configure NVIDIA settings
#   git                     Personal config
#   yay                     Pacman wrapper and AUR helper
#       base-devel              Pacakage group for installing AURs
#   curl                    Transfer data

# Personal
#   pulseaudio              Sound server
#   firefox                 Web browser
#   spotify                 Music player
#   discord                 Voice and text chat app

########################################

# dotfiles related packages
########################################
sudo pacman -S --noconfirm xorg xorg-server xorg-xinit
sudo pacman -S --noconfirm i3-gaps rofi feh playerctl xautolock
sudo pacman -S --noconfirm picom
sudo pacman -S --noconfirm alacritty
sudo pacman -S --noconfirm zsh gnu-free-fonts
sudo pacman -S --noconfirm neovim
sudo pacman -S --noconfirm tmux
sudo pacman -S --noconfirm nvidia nvidia-settings
sudo pacman -S --noconfirm git base-devel curl

# install yay
mkdir $HOME/aur
git clone https://aur.archlinux.org/yay.git $HOME/yay
cd $HOME/yay
makepkg -si --noconfirm
cd -

yay -S --noconfirm polybar
yay -S --noconfirm betterlockscreen
yay -S --noconfirm dbus-python
yay -S --noconfirm nerd-fonts-source-code-pro

$HOME/dotfiles/scripts/symlink
$HOME/dotfiles/scripts/setup


# personal packages
########################################
sudo pacman -S --noconfirm sudo
sudo pacman -S --noconfirm pulseaudio
sudo pacman -S --noconfirm discord
sudo pacman -S --noconfirm firefox
sudo pacman -S --noconfirm gimp
sudo pacman -S --noconfirm btop
yay -S --noconfirm spotify

# udpate any packages
yay

# start
########################################
# load nvidia settings
nvidia-settings --load-config-only

ln -s $HOME/dotfiles/.xinitrc $HOME/.xinitrc

startx


# steps to do manually
########################################
# apply flat mouse acceleration profile
#https://wiki.archlinux.org/title/Mouse_acceleration#Disabling_mouse_acceleration

# configure nvidia-settings to update refresh rate, monitor layout, etc. and save to xorg.conf
