#!/bin/bash

sudo pacman -S i3-gaps dmenu feh playerctl xautolock picom alacritty zsh neovim tmux curl git base-devel

# install yay
mkdir $HOME/aur
git clone https://aur.archlinux.org/yay.git $HOME/aur/yay
cd $HOME/aur/yay
makepkg -si
cd -

yay -S polybar betterlockscreen dbus-python

$HOME/dotfiles/scripts/setup
$HOME/dotfiles/scripts/symlink
