#!/bin/bash

# dotfiles related packages
########################################
sudo pacman -S xorg xorg-server xorg-xinit i3-gaps dmenu feh playerctl xautolock picom alacritty zsh neovim tmux python curl git base-devel gnu-free-fonts

# install yay
mkdir $HOME/aur
git clone https://aur.archlinux.org/yay.git $HOME/yay
cd $HOME/yay
makepkg -si
cd -

yay -S polybar betterlockscreen dbus-python

# create .xinitrc file
echo '#!/bin/bash\nexec i3' > $HOME/.xinitrc

$HOME/dotfiles/scripts/setup
$HOME/dotfiles/scripts/symlink


# personal packages
########################################
sudo pacman -S pulseaudio discord firefox
yay -S spotify


# start
########################################
startx
