#!/bin/bash

# install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc

# install powerlevel10k for zsh
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# change default shell to zsh
chsh -s $(which zsh)

# install vim-plug for neovim
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# install neovim plugins
nvim -c 'PlugInstall --sync' +qa

# enable gdm
sudo systemctl enable gdm.service
# this fixes gdm login not on primary monitor
sudo cp -f ~/.config/monitors.xml ~gdm/.config/monitors.xml
sudo chown $(id -u gdm):$(id -g gdm) ~gdm/.config/monitors.xml

# enable cups
sudo systemctl enable cups.service
sudo systemctl start cups.service

# apply flat mouse acceleration profile
#https://wiki.archlinux.org/title/Mouse_acceleration#Disabling_mouse_acceleration
sudo ln -s ./install/50-mouse-acceleration.conf /etc/X11/xorg.conf.d/50-mouse-acceleration.conf


# steps to do manually
########################################
# configure nvidia-settings to update refresh rate, monitor layout, etc. and save to xorg.conf

# mount other NTFS file system from Windows to be able to access files and installed Steam games
#   this is done by adding entries to /etc/fstab after installing the ntfs-3g package
#       example entry below (note uid and gid instead of defaults to allow all permissions)
# /dev/sda2 (HD)
#UUID=<UUID>               /<mount location>     ntfs-3g     uid=1000,gid=1000   0 0

# cups
# add printer

# steam
# enable multilib repository in /etc/pacman.conf
