#!/bin/bash

# Script to iterate over dotfiles and directories and symlink to $HOME and $HOME/.config respectively

# Allows iteration over dotfiles
GLOBIGNORE=.

EXCLUDE_FILES=("README.md")
EXCLUDE_DIRS=(".git" "scripts")

set DOTFILES=$HOME/dotfiles

for item in $DOTFILES/*; do
    # file
    if [[ -f $item ]]; then
        # get file basename
        file=$(basename ${item})

        # check to exclude file
        exclude=0
        for excl in "${EXCLUDE_FILES[@]}"; do
            if [[ $file == $excl ]]; then
                exclude=1
            fi
        done

        if (( $exclude == 0 )); then
            # check if file exists in $HOME
            if [[ -f $HOME/$file ]]; then
                echo "Removing $HOME/$file"
                rm -f "$HOME/$file"
            fi

            echo "Symlink $item -> $HOME/$file"
            ln -s "$item" "$HOME/$file"
        fi
    # directory
    elif [[ -d $item ]]; then
        # get dir basename
        dir=$(basename ${item})

        # check to exclude dir
        exclude=0
        for excl in "${EXCLUDE_DIRS[@]}"; do
            if [[ $dir == $excl ]]; then
                exclude=1
            fi
        done

        if (( $exclude == 0 )); then
            # check if dir exists in $HOME/.config
            if [[ -d $HOME/.config/$dir ]]; then
                echo "Removing $HOME/.config/$dir"
                rm -rdf "$HOME/.config/$dir"
            fi

            echo "Symlink $item -> $HOME/.config/$dir"
            ln -s "$item" "$HOME/.config/$dir"
        fi
    fi
done
